---
name: Perl6-Feeds
version: 0.11
author:
  - 'Eric Strom <ejstrom@gmail.com>'
abstract: implements perl6 feed operators in perl5 via source filtering
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.35
provides:
  Perl6::Feeds:
    file: lib/Perl6/Feeds.pm
    version: 0.11
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
